In [2]:
!pip install "pandas <3.0.0"

Collecting pandas<3.0.0
  Downloading pandas-2.3.3-cp314-cp314-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl.metadata (91 kB)
Requirement already satisfied: numpy>=1.26.0 in /home/vscode/.local/lib/python3.14/site-packages (from pandas<3.0.0) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/python/3.14.4/lib/python3.14/site-packages (from pandas<3.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/vscode/.local/lib/python3.14/site-packages (from pandas<3.0.0) (2023.3)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/python/3.14.4/lib/python3.14/site-packages (from pandas<3.0.0) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/python/3.14.4/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas<3.0.0) (1.17.0)
Downloading pandas-2.3.3-cp314-cp314-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 12.5 MB/s  0:00:00 eta 0:00:01
Installing collected packages: pandas
Successfully installed pandas-2.3.3

In [ ]:
from pydantic import BaseModel, Field

In [3]:
from pathlib import Path
import sys

repo = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(repo))
sys.path.insert(0, str(repo / "custom_components"))

from custom_components.irrigation_monitor.util import *

In [4]:
flume_user="onuruno.e@gmail.com"
flume_pass="hocry5-jytmec-byvVuf"
flume_client_id="93019L97TASVPN7"
flume_client_secret="RA9WBEL3N4WTXTCH1QSK"
rachio_token="0e3299ee-ca87-4c2e-b8fa-e2636c15202a"

In [15]:
flume_client = FlumeClient(flume_user, flume_pass, flume_client_id, flume_client_secret)

In [16]:
rachio_client = RachioClient(rachio_token)

In [19]:
rachio_client.get_last_watered_summary()

,zone_id,zone_name,last_watering_start_time,last_watering_stop_time,est_gallons_per_minute,est_gallons_used,sqft,enabled
0,11,11: south back fence,2026-05-01 08:00:01-07:00,2026-05-01 08:27:16-07:00,2.201000,59.977250,142,True
1,9,9: Raised beds and berries,2026-05-03 06:10:02-07:00,2026-05-03 06:11:01-07:00,4.251133,4.180281,187,True
2,10,10: Fruit trees,2026-03-21 20:30:02-07:00,2026-03-21 21:02:41-07:00,12.400000,404.860000,300,True
3,7,7: northeast slope,2026-04-29 05:40:49-07:00,2026-04-29 05:59:59-07:00,0.578667,11.091111,28,True
4,4,4: old raised beds,2025-09-23 18:01:03-07:00,2025-09-23 18:02:37-07:00,4.251133,6.660109,187,True
5,5,5: Native Garden,2025-08-04 03:34:11-07:00,2025-08-04 06:00:02-07:00,2.325000,339.101250,750,True
6,1,1: front succulent,2026-03-15 12:07:52-07:00,2026-03-15 12:52:22-07:00,4.908333,218.420833,950,True
7,12,12: North Wall,2026-05-02 20:30:02-07:00,2026-05-02 20:39:06-07:00,8.525000,77.293333,550,True

In [13]:
res = poll_for_irrigation_usage(
    flume_user,
    flume_pass,
    flume_client_id,
    flume_client_secret,
    rachio_token,
    flume_device_index=0,
)

In [14]:
res

,zone_name,total_gallons,total_watering_minutes,gallons_per_minute,zone_id,last_watering_start_time,last_watering_stop_time,est_gallons_per_minute,est_gallons_used,sqft,enabled
0,7: northeast slope,18.852517,19.0,0.992238,7,2026-04-29 05:40:49-07:00,2026-04-29 05:59:59-07:00,0.578667,11.091111,28,True
1,12: North Wall,54.027080,9.0,6.003009,12,2026-05-02 20:30:02-07:00,2026-05-02 20:39:06-07:00,8.525000,77.293333,550,True
2,9: Raised beds and berries,3.568872,1.0,3.568872,9,2026-05-03 06:10:02-07:00,2026-05-03 06:11:01-07:00,4.251133,4.180281,187,True
3,11: south back fence,34.569669,27.0,1.280358,11,2026-05-01 08:00:01-07:00,2026-05-01 08:27:16-07:00,2.201000,59.977250,142,True
4,1: front succulent,411.932542,45.0,9.154056,1,2026-03-15 12:07:52-07:00,2026-03-15 12:52:22-07:00,4.908333,218.420833,950,True
5,4: old raised beds,0.564567,1.0,0.564567,4,2025-09-23 18:01:03-07:00,2025-09-23 18:02:37-07:00,4.251133,6.660109,187,True
6,5: Native Garden,509.360737,146.0,3.488772,5,2025-08-04 03:34:11-07:00,2025-08-04 06:00:02-07:00,2.325000,339.101250,750,True
7,10: Fruit trees,662.086290,32.0,20.690197,10,2026-03-21 20:30:02-07:00,2026-03-21 21:02:41-07:00,12.400000,404.860000,300,True